// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `base.templ`, Line: 9, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"><link href=\"https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/themes/prism.min.css\" rel=\"stylesheet\"><style>\r\n\t\t\t.hero-section {\r\n\t\t\t\tbackground: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n\t\t\t\tcolor: white;\r\n\t\t\t\tpadding: 4rem 0;\r\n\t\t\t}\r\n\t\t\t.feature-card {\r\n\t\t\t\ttransition: transform 0.2s ease-in-out;\r\n\t\t\t\tborder: none;\r\n\t\t\t\tbox-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n\t\t\t}\r\n\t\t\t.feature-card:hover {\r\n\t\t\t\ttransform: translateY(-5px);\r\n\t\t\t\tbox-shadow: 0 8px 15px rgba(0, 0, 0, 0.2);\r\n\t\t\t}\r\n\t\t\t.code-block {\r\n\t\t\t\tbackground: #f8f9fa;\r\n\t\t\t\tborder-radius: 8px;\r\n\t\t\t\tpadding: 1rem;\r\n\t\t\t\tmargin: 1rem 0;\r\n\t\t\t}\r\n\t\t\t.navbar-brand {\r\n\t\t\t\tfont-weight: bold;\r\n\t\t\t\tfont-size: 1.5rem;\r\n\t\t\t}\r\n\t\t</style></head><body><nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\"><div class=\"container\"><a class=\"navbar-brand\" href=\"/\"><i class=\"bi bi-code-square\"></i> Templ Demo</a><div class=\"navbar-nav ms-auto\"><a class=\"nav-link\" href=\"/\">Home</a> <a class=\"nav-link\" href=\"/components\">Components</a> <a class=\"nav-link\" href=\"/todo\">Todo App</a> <a class=\"nav-link\" href=\"/users\">Users</a></div></div></nav><main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main><footer class=\"bg-dark text-white py-4 mt-5\"><div class=\"container text-center\"><p>&copy; 2025 Templ Demo - Type-safe HTML templating for Go</p></div></footer><script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script><script src=\"https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/components/prism-core.min.js\"></script><script src=\"https://cdnjs.cloudflare.com/ajax/libs/prism/1.24.1/plugins/autoloader/prism-autoloader.min.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
